server:
  port: 9292

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, metrics

  endpoint:
    health:
      show-details: always

resilience4j:

  circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  ratelimiter:
    instances:
      userService:
        limitForPeriod: 100
        limitRefreshPeriod: 1s
        timeoutDuration: 0s
        registerHealthIndicator: true
        eventConsumerBufferSize: 100

  timelimiter:
    instances:
      userService:
        timeoutDuration: 5s
        cancelRunningFuture: true

  bulkhead:
    instances:
      userService:
        max-concurrent-calls: 3
        max-wait-duration: 0s

  thread-pool-bulkhead:
    instances:
      userService:
        max-thread-pool-size: 3
        core-thread-pool-size: 1
        queue-capacity: 0
